### PR TITLE
Application Deploy

### PR DESCRIPTION
**Pull request by Kidd254**
in this pull request i added a link to my desktop version on the READ ME file

### CODE REVIEW

**Review by pinkmoon25 — CHANGES_REQUESTED** [review]
Hi @Kidd254 , 

Good job so far! you have done well deploying the portfolio with github pages
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
linter checks :heavy_check_mark: 
Professional Readme :heavy_check_mark: 
Live demo link added to Readme :heavy_check_mark: 

## Required Changes ♻️
**As one of the requirement is to make sure our live demo of our portfolio is working well, currently the live version has some bugs please fix it before we can successfully move on to the next project** 

**Please fix the below issues in your live demo of the portfolio** :point_down: 
**The header is moving out of the viewport and the contact link is not in the viewport please see** :point_down: 
image

**Please fix the projects cards as the images are not rendered please see** :point_down: 
image



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kidd254** [comment]
@PinkMoon25 how do i fix the images... after deployment, the images have disappeared

**Comment by pinkmoon25** [comment]
Hi @Kidd254, I saw that your images folder begins with a '.' which is generally used for hidden folders, please try removing the . From your images folder name and correct your image file path in the src attributes and see if that fixes the issue

**Review by Owusu-Desmond — APPROVED** [review]
Hi @Kidd254 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
